GET http://localhost:3001/api/persons

###
DELETE  http://localhost:3001/api/persons/611edc174882802fde88e6dc
 

###
POST  http://localhost:3001/api/persons
Content-Type: application/json

{
  "name": "Ioana Frincu",
  "number": "0000 9999 1000"
}